# Generated by Django 4.2.11 on 2024-04-03 07:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhar_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_user_id',
            field=models.CharField(default=uuid.UUID('1f8acd25-c033-4075-9677-dd09b158893a'), editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
