# Generated by Django 4.2.11 on 2024-04-03 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0003_alter_user_unique_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emidetail',
            name='interest_for_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='unique_user_id',
            field=models.CharField(default=uuid.UUID('ac930da5-7b01-4b39-a5f6-e3cd1bbe5c75'), editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
