# Generated by Django 4.2.11 on 2024-04-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0004_emidetail_interest_for_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_user_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
